#11-2-1 用 OpenCV 讀取並顯示圖片

In [10]:
# 執行本章各行範例前, 請先執行此儲存格, 確認 cv2 已確實匯入
# 執行本章各行範例前, 請先執行此儲存格, 確認 cv2 已確實匯入
# 執行本章各行範例前, 請先執行此儲存格, 確認 cv2 已確實匯入
import numpy as np
import cv2

#import matplotlib.pyplot as plt
#
#def aidemy_imshow(name, img):
#    b, g, r = cv2.split(img)
#    img = cv2.merge([r, g, b])
#    plt.title(name)
#    plt.imshow(img)
#    plt.show()

#cv2.imshow = aidemy_imshow

In [11]:
cv2.namedWindow("sample")
sample = cv2.imread(r'./photo/sample.jpg')  # 請依11-2-1節的說明，換成您自己的雲端硬碟路徑
print(type(sample))
print(sample.shape)
cv2.imshow('Sample pic', sample)
cv2.waitKey(0)
cv2.destroyAllWindows()


<class 'numpy.ndarray'>
(873, 1309, 3)


In [12]:
#讀入 sample2.jpg  顯示 sample2.jpg
# 你的程式碼

cv2.namedWindow("sample2")
sample2 = cv2.imread(r'./photo/sample2.jpg')  # 請依11-2-1節的說明，換成您自己的雲端硬碟路徑
print(type(sample2))
print(sample2.shape)
cv2.imshow('sample2 pic', sample2)
cv2.waitKey(0)
cv2.destroyAllWindows()


<class 'numpy.ndarray'>
(943, 1414, 3)


In [13]:
img_resize = cv2.resize(sample, (sample.shape[1] //2, sample.shape[0] //2))
print(img_resize.shape)
cv2.imshow('Sample pic', img_resize)
cv2.waitKey(0)
cv2.destroyAllWindows()


(436, 654, 3)


In [14]:
#讀入 sample2.jpg  長寬各放大2倍  sample2.jpg
# 你的程式碼
img_resize2 = cv2.resize(sample2, (sample2.shape[1] * 2, sample2.shape[0] * 2))
print(img_resize2.shape)
cv2.imshow('Sample pic', img_resize2)
cv2.waitKey(0)
cv2.destroyAllWindows()


(1886, 2828, 3)


#11-2-6 圖片旋轉

In [15]:
aff_matrix = cv2.getRotationMatrix2D((sample.shape[1]/2, sample.shape[0]/2), 30, 0.8)

print(type(aff_matrix))
print(aff_matrix.shape)
print (aff_matrix)
print(sample.shape)
img_rotate = cv2.warpAffine(sample, aff_matrix, (sample.shape[1], sample.shape[0]))
cv2.imshow('Sample pic', img_rotate)
cv2.waitKey(0)
cv2.destroyAllWindows()


<class 'numpy.ndarray'>
(2, 3)
[[  0.69282032   0.4         26.44909858]
 [ -0.4          0.69282032 395.883929  ]]
(873, 1309, 3)


In [16]:
# 讀入 sample2.jpg  旋轉 45 度 縮小 成 0.5倍
# 你的程式碼
aff_matrix = cv2.getRotationMatrix2D((sample2.shape[1]/2, sample2.shape[0]/2), 45, 0.5)

print(type(aff_matrix))
print(aff_matrix.shape)
print(aff_matrix)
print(sample2.shape)
img_rotate = cv2.warpAffine(sample2, aff_matrix, (sample2.shape[1], sample2.shape[0]))
cv2.imshow('sample2 pic', img_rotate)
cv2.waitKey(0)
cv2.destroyAllWindows()


<class 'numpy.ndarray'>
(2, 3)
[[ 3.53553391e-01  3.53553391e-01  2.90337329e+02]
 [-3.53553391e-01  3.53553391e-01  5.54761823e+02]]
(943, 1414, 3)


#11-3-3 模糊效果

In [17]:
Img_blur = cv2.GaussianBlur(sample, (11, 11), 3)

cv2.imshow('Sample pic', Img_blur)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [18]:
# # 讀入 sample2.jpg  旋轉 用 (22,22) 矩陣做模糊效果
# 你的程式碼
Img_blur2 = cv2.GaussianBlur(sample2, (23, 23), 0) #內核只能用基數 無法用22

cv2.imshow('Sample2 pic', Img_blur2)
cv2.waitKey(0)
cv2.destroyAllWindows()


#11-3-4 去除圖片的雜訊

In [19]:
img2 = cv2.imread(r'./photo/sample2.jpg')   #請依11-2-1節的說明，換成您自己的雲端硬碟路徑
cv2.imshow('Sample pic', img2)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [20]:


img2_denoised = cv2.fastNlMeansDenoisingColored(img2, h=5)

cv2.imshow('Sample pic', img2_denoised)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [21]:
# 讀入 sample.jpg  去除圖片的雜訊
# 你的程式碼
img3 = cv2.imread(r'./photo/sample.jpg')  # 請依11-2-1節的說明，換成您自己的雲端硬碟路徑
cv2.imshow('Sample pic', img3)
cv2.waitKey(0)
cv2.destroyAllWindows()


img3_denoised = cv2.fastNlMeansDenoisingColored(img3, h=5)

cv2.imshow('Sample pic', img3_denoised)
cv2.waitKey(0)
cv2.destroyAllWindows()
exit(0)
